### ISSUE TITLE
TypeError in Demo (Safari)

### ISSUE THREAD

**Issue by endwaa** [Avexis/fontalizer#2]
Typing in Demo raises this error:

```
TypeError: undefined is not an object (evaluating 'event.key.match')
onKeyDown - script.js:28
```
```javascript
function onKeyDown(event) {
        if (checkBackspace(event)) {
            return;
        }
        // **LINE 28**
        if (!event.key.match(reg) && event.keyCode !== 13 && event.keyCode !== 32) { 
            return;
        }
        for (var i = 0; i < keysPressed.length; i++) {
            if (keysPressed[i].key === event.keyCode) {
                return;
            }
        }
```

```
Browser: Safari 10.0
OS: OSX El Capitan 10.11.6
```

**Comment by boyum** [comment]
Thanks for filing the issue. This has been noted, but we weren't to keen on doing a large `switch` just to make Safari 10.0 happy. We might still, even though `KeyEvent.key` is included in the latest version of Safari (10.1), as we don't know how long it will be for it to be pushed out to the public. Could you maybe try upgrading your browser and try it out? To be honest, I don't know too much about Apple's push habits.
